import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/lib/providers/ConvexClientProvider";
import Header from "@/components/Header";
import SyncUserWithConvex from "@/lib/providers/SyncUserWithConvex";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased py-6 px-4`}
      ><ConvexClientProvider>
        <ClerkProvider>
          <Header/>
          <SyncUserWithConvex/>
          <Toaster/>
          {children}
      </ClerkProvider>
      </ConvexClientProvider>
        
      </body>
    </html>
  );
}
